### ISSUE TITLE
Please refine community guidelines

### ISSUE THREAD

**Issue by holtgrewe** [urmi-21/ORIS#10]
RE https://github.com/openjournals/joss-reviews/issues/1589

> Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

While point 2&3 are solved by the README statement "Please report all the bugs through GitHub here.", the first appears to be not addressed.

**Comment by urmi-21** [comment]
To address this, I've added CONTRIBUTING.md.

**Comment by holtgrewe** [comment]
Excellent, thanks.

**Comment by holtgrewe** [comment]
Ah, sorry for closing this prematurely.

I think I don't understand the technical prerequisites for contributing. Do I have to use some IDE? How to build this? What are library dependencies here?

This should probably be part of the CONTRIBUTING file, documenting in text without figures is sufficient. It would be great if you could walk a potential contributor from cloning the repository to building and running the actual app.

**Comment by urmi-21** [comment]
Thanks for the suggestions. I have updated the CONTRIBUTING.md file.
