### ISSUE TITLE
Software Engineering Suggestions

### ISSUE THREAD

**Issue by holtgrewe** [urmi-21/ORIS#12]
I have not looked at the code in detail but regarding meta project stuff, I have some suggestions.

- Maybe include a `HISTORY.md` file that outlines changes between versions?
- You bind contributors closely to Netbeans.
  Using an independent build system such as Maven would decouple building from development.
- This would also facilitate using a continuous integration services such as Travis CI which...
- ... together with automated tests (e.g., using JUnit) would allow ensuring that your software continuous doing what you expect in later versions and make you more confident in acception user contributions.

These points are not part of the JOSS review, just some suggestions. I won't have time to follow up on these but in case you have any questions you'll probably find good explanation and tutorials for each on Google.

Best wishes,

**Comment by urmi-21** [comment]
Hi, thanks for these great suggestions. I agree from a software engineering perspective this software could be improved a lot. This was, in fact, my first java project. I have learned how to design better systems since then.
