### ISSUE TITLE
Please include build instuctions

### ISSUE THREAD

**Issue by jdeligt** [urmi-21/ORIS#13]
Please add build instructions for those users that would like to check out the code and build themselves. A precompiled jar is subject to injections, i.e. not guaranteed to be the source of the repo.

**Comment by urmi-21** [comment]
Hi, the building instructions here: https://github.com/urmi-21/ORIS/blob/master/CONTRIBUTING.md

**Comment by jdeligt** [comment]
Hi, thanks for pointing that out. Not where I expected them. Could you refer to it from the install instructions or do you want it there so only contributors have to see it?

**Comment by urmi-21** [comment]
I have added a building section in the readme which points to the contributing file

**Comment by jdeligt** [comment]
Thanks for that, that should make it easier to find.
