### ISSUE TITLE
Improve layout of figures and tables in ORIS_SI.pdf

### ISSUE THREAD

**Issue by holtgrewe** [urmi-21/ORIS#6]
I find the article a bit hard to read as all figures are put towards the end.

Would it be possible to put them a bit closer to where they are referenced?

On another note: would it be possible to include the sources of these documents (maybe I'm overloooking them)?

**Comment by holtgrewe** [comment]
RE https://github.com/openjournals/joss-reviews/issues/1589

**Comment by urmi-21** [comment]
I can give it a try (to make figures more in line with the text). 
I am not sure what you mean by:

> would it be possible to include the sources of these documents

**Comment by holtgrewe** [comment]
What I mean here whether it is possible to upload the markdown/latex sources but that's actually just a suggestion (as the rest of this ticket, feel free to close it if you consider this overkill).

**Comment by urmi-21** [comment]
I have updated the _ORIS_SI.pdf_. Closing this issue now.
