### ISSUE TITLE
The main window cannot be resized

### ISSUE THREAD

**Issue by holtgrewe** [urmi-21/ORIS#7]
On Windows with a high resolution monitor, the lines wrap yet I cannot resize the window. I'm feeling like I'm not using my screen real estate to the fullest.

![image](https://user-images.githubusercontent.com/521780/61753213-cd318480-adae-11e9-9dde-56092ceff0b1.png)

**Comment by holtgrewe** [comment]
RE https://github.com/openjournals/joss-reviews/issues/1589

**Comment by urmi-21** [comment]
I have increased the window size to better display a typical _fasta_ file (please download ORIS again). Sorry, the main window still can't be resized (this was how it was planned and designed). I may address the resizing issue in the future. For now, I would like to add that this issue doesn't significantly affect the core functionality of the software.

**Comment by holtgrewe** [comment]
Closing this, although no JAR file is available for 1.0.1 yet.
