### ISSUE TITLE
Complete documentation of functionality

### ISSUE THREAD

**Issue by holtgrewe** [urmi-21/ORIS#8]
While there are pretty usage videos in the README, it would be nice to have some more user-level documentation describing the different menu entries and dialogues and what they have. In particular, if I have to provide some feature table or "Glimmer" file, it would be nice to have at least some pointers where or how I could obtain such a file.

**Comment by holtgrewe** [comment]
RE https://github.com/openjournals/joss-reviews/issues/1589

**Comment by urmi-21** [comment]
For now, I have provided a user guide https://github.com/urmi-21/ORIS/blob/master/OrisGuide.pdf which documents the functionalities.
In its current state, the user guide doesn't all the details which could be there (e.g., how to get an output from glimmer). I plan to work on this in the future.

But I would like to know your opinion if you think this documentation is below the accepted standard.
Thanks

**Comment by holtgrewe** [comment]
Maybe link to the user guide directly in the README file?

Please take the following as a suggestion only:

I usually find it useful to have an "for the impatient" section at the top of the README. E.g.

```
## For the Impatient

- License: XXX
- Requirements: Operating system XXX, Java XXX
- Installation: Download ZIP from Releases, unpack and double-click JAR file.
- User Documentation: See [link to user guide]

More details can be found below.
```

**Comment by urmi-21** [comment]
Hi, a link to the user guide is already provided in the README file under the Getting Started section.

**Comment by holtgrewe** [comment]
OK, from my point of view, the program does what it's advertised to do.
