### ISSUE TITLE
Automated or manual tests

### ISSUE THREAD

**Issue by holtgrewe** [urmi-21/ORIS#9]
RE https://github.com/openjournals/joss-reviews/issues/1589

It is hard to verify that the functionality of the software works as described. First of all, not all functionality is described (cf. #8) but also there neither are automated/CI tests nor are there instructions for the functionalities to be tested.

I think that's a petty. The software appears to provide a large number of features but documentation and tests appear to be a bit lower than the standard of the features themselves.

**Comment by urmi-21** [comment]
Hi, I agree that there are no automated test sets for ORIS.
But I have pointed out a manual way which lets the user test (or validate) the results produced by ORIS (see https://github.com/urmi-21/ORIS/tree/master/test). I have suggested to use ORIS’ automatic prediction module. This executes the skew, correlation, entropy and motif searching methods. The output produced then could be validated against known or expected output. 

Further, in the case study performed, we have comprehensively tested ORIS using bacterial and archeal genome. The results are compared to previously experimentally validated and published results. We also compared ORIS with other software and tools and the results demonstrate that ORIS is able to find the correct origin of replication sequences in the given genomes.
Another, example for validation of ORIS’ result is the work published by Agarwal et. al. (https://www.ncbi.nlm.nih.gov/pubmed/28644560). In this work ORIS predicted putative origin of replication sites in the genome of Plasmodium falciparum. The computational results were later experimentally verified.

I hope this is sufficient evidence to confirm the functionality of the software and judge the correctness of the results produced by ORIS. I have also updated the test document (see https://github.com/urmi-21/ORIS/tree/master/test) to reflect this information.

Please let me know what you think.

**Comment by holtgrewe** [comment]
IMO it is sufficient but not obvious to find.

Please link to the tests directory and the contained README from the main README.

**Comment by urmi-21** [comment]
I have updated the README file.

**Comment by holtgrewe** [comment]
OK, I have tested the program now and it generates output similar to the GIF in the README. I trust that this makes sense in the application domain (that I have no knowledge about) ;)

Reading through the user guide, it might make sense to include some more information on how to interpret the results. If "wet-lab biologists" are to use the software they might welcome help of how to interpret the "dry-lab" results that your program gives.
